/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TestSupabaseRouteImport } from './routes/test-supabase'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as ChatsNewRouteImport } from './routes/chats/new'
import { Route as ChatsSessionIdRouteImport } from './routes/chats/$sessionId'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSupabaseRoute = TestSupabaseRouteImport.update({
  id: '/test-supabase',
  path: '/test-supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsNewRoute = ChatsNewRouteImport.update({
  id: '/chats/new',
  path: '/chats/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsSessionIdRoute = ChatsSessionIdRouteImport.update({
  id: '/chats/$sessionId',
  path: '/chats/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/update-password': typeof UpdatePasswordRoute
  '/chats/$sessionId': typeof ChatsSessionIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/chats': typeof ChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/update-password': typeof UpdatePasswordRoute
  '/chats/$sessionId': typeof ChatsSessionIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/chats': typeof ChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/update-password': typeof UpdatePasswordRoute
  '/chats/$sessionId': typeof ChatsSessionIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/chats/': typeof ChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/test-supabase'
    | '/update-password'
    | '/chats/$sessionId'
    | '/chats/new'
    | '/chats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/test-supabase'
    | '/update-password'
    | '/chats/$sessionId'
    | '/chats/new'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/test-supabase'
    | '/update-password'
    | '/chats/$sessionId'
    | '/chats/new'
    | '/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TestSupabaseRoute: typeof TestSupabaseRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ChatsSessionIdRoute: typeof ChatsSessionIdRoute
  ChatsNewRoute: typeof ChatsNewRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-supabase': {
      id: '/test-supabase'
      path: '/test-supabase'
      fullPath: '/test-supabase'
      preLoaderRoute: typeof TestSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/new': {
      id: '/chats/new'
      path: '/chats/new'
      fullPath: '/chats/new'
      preLoaderRoute: typeof ChatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$sessionId': {
      id: '/chats/$sessionId'
      path: '/chats/$sessionId'
      fullPath: '/chats/$sessionId'
      preLoaderRoute: typeof ChatsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TestSupabaseRoute: TestSupabaseRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ChatsSessionIdRoute: ChatsSessionIdRoute,
  ChatsNewRoute: ChatsNewRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
